# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:

        avatar:
            quality: 75
            filters:
                # use and setup the "fixed" filter
                thumbnail: { size: [30, 30], mode: outbound }

        card:
            quality: 75
            filters:
                # use and setup the "fixed" filter
                thumbnail: { size: [350, 350], mode: outbound }