vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads/article_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true 

        header_image:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads/header_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true 